//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyncTAT
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAIS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PAIS()
        {
            this.CLIENTE = new HashSet<CLIENTE>();
            this.IIMPUESTO = new HashSet<IIMPUESTO>();
        }
    
        public string LAND { get; set; }
        public string SPRAS { get; set; }
        public string LANDX { get; set; }
        public string IMAGE { get; set; }
        public bool ACTIVO { get; set; }
        public string SOCIEDAD_ID { get; set; }
        public string DECIMAL { get; set; }
        public string MILES { get; set; }
        public bool BACKORDER { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLIENTE> CLIENTE { get; set; }
        public virtual SOCIEDAD SOCIEDAD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IIMPUESTO> IIMPUESTO { get; set; }
    }
}
