//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyncTAT
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOCIEDAD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SOCIEDAD()
        {
            this.PAIS = new HashSet<PAIS>();
        }
    
        public string BUKRS { get; set; }
        public string BUTXT { get; set; }
        public string ORT01 { get; set; }
        public string LAND { get; set; }
        public string SUBREGIO { get; set; }
        public string WAERS { get; set; }
        public string SPRAS { get; set; }
        public string NAME1 { get; set; }
        public string KTOPL { get; set; }
        public bool ACTIVO { get; set; }
        public string REGION { get; set; }
    
        public virtual MONEDA MONEDA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PAIS> PAIS { get; set; }
    }
}
