//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyncTAT
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=TAT001Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MATERIAL> MATERIAL { get; set; }
        public virtual DbSet<SOCIEDAD> SOCIEDAD { get; set; }
        public virtual DbSet<TCAMBIO> TCAMBIO { get; set; }
        public virtual DbSet<CLIENTE> CLIENTE { get; set; }
        public virtual DbSet<IMPUESTO> IMPUESTO { get; set; }
        public virtual DbSet<MONEDA> MONEDA { get; set; }
        public virtual DbSet<PAIS> PAIS { get; set; }
        public virtual DbSet<UMEDIDA> UMEDIDA { get; set; }
        public virtual DbSet<IIMPUESTO> IIMPUESTO { get; set; }
        public virtual DbSet<MATERIALT> MATERIALT { get; set; }
        public virtual DbSet<MATERIALVKE> MATERIALVKE { get; set; }
        public virtual DbSet<PROVEEDOR> PROVEEDOR { get; set; }
        public virtual DbSet<UMEDIDAT> UMEDIDAT { get; set; }
        public virtual DbSet<MATERIALGP> MATERIALGP { get; set; }
        public virtual DbSet<MATERIALGPT> MATERIALGPT { get; set; }
        public virtual DbSet<CUENTAGL> CUENTAGL { get; set; }
        public virtual DbSet<CUENTAA> CUENTAA { get; set; }
    }
}
